MCDropout: true
accelerator: gpu
batchnorm: false
calibration: false
data_split:
- 200
- 50
- 50
devices: 1
input_dropout: 0
hidden_dropout: 0.1
edge_cut: 0.5
factor: 0.8
hard_cuts:
  pt:
  - 1000.0
  - .inf
hidden: 1024
hidden_activation: ReLU
input_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/pt>1GeV/200/metric_learning/
layernorm: true
lr: 0.001
max_epochs: 300
metric_mode: max
metric_to_monitor: auc
model: Filter
n_train: 200
nb_MCD_passes: 100
nb_layer: 4
node_features:
- r
- phi
- z
- cell_count
- cell_val
- leta
- lphi
- lx
- ly
- lz
- geta
- gphi
node_scales:
- 1000
- 3.14
- 1000
- 1
- 1
- 1
- 1
- 0.1
- 1
- 0.1
- 1
- 3.14
nodes: 1
patience: 10
project: UQ_MCD_pt>1GeV_filter_200
ratio: 0
scheduler: StepLR
stage: edge_classifier
stage_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/pt>1GeV/200/filter/
undirected: true
warmup: 10
weighting:
- conditions:
    y: false
  weight: 1.0
- conditions:
    y: true
  weight: 0.0
- conditions:
    nhits:
    - 3.0
    - .inf
    pt:
    - 1000.0
    - .inf
    y: true
  weight: 2.0
