accelerator: gpu
batchnorm: false
data_split:
- 50
- 50
- 50
devices: 4
edge_cut: 0.5
factor: 0.8
hard_cuts:
  track_particle_pt:
  - 0.0
  - .inf
hidden: 1024
hidden_activation: ReLU
hidden_dropout: 0.1
input_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/all_pt/50/metric_learning/
input_dropout: 0
layernorm: true
lr: 0.001
max_epochs: 300
metric_mode: max
metric_to_monitor: auc
model: Filter
nb_layer: 4
node_features:
- hit_r
- hit_phi
- hit_z
- hit_cell_count
- hit_cell_val
- hit_leta
- hit_lphi
- hit_lx
- hit_ly
- hit_lz
- hit_geta
- hit_gphi
node_scales:
- 1000
- 3.14
- 1000
- 1
- 1
- 1
- 1
- 0.1
- 1
- 0.1
- 1
- 3.14
nodes: 1
patience: 10
project: UQ_MCD_all_pt_filter_50_HightPT_targets
ratio: 5
scheduler: StepLR
stage: edge_classifier
stage_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/all_pt/50/filter/
undirected: true
warmup: 10
weighting:
- conditions:
    edge_y: false
  weight: 1.0
- conditions:
    edge_y: true
  weight: 0.0
- conditions:
    edge_y: true
    track_particle_nhits:
    - 3.0
    - .inf
    track_particle_pt:
    - 1000.0
    - .inf
  weight: 2.0
