MCDropout: true
accelerator: gpu
aggregation: sum
batchnorm: false
calibration: false
data_split:
- 400
- 50
- 50
devices: 1
dropout: 0.1
edge_cut: 0.5
input_cut: 0.1
factor: 0.9
hard_cuts:
  pt:
  - 1000.0
  - .inf
hidden: 128
hidden_activation: SiLU
input_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/pt>1GeV/400/filter/
layernorm: true
lr: 0.001
max_epochs: 400
model: InteractionGNN
n_graph_iters: 8
n_train: 400
nb_MCD_passes: 100
nb_edge_layer: 2
nb_node_layer: 2
node_features:
- r
- phi
- z
node_scales:
- 1000
- 3.14
- 1000
nodes: 1
output_activation: Tanh
patience: 10
project: UQ_MCD_pt>1GeV_gnn_400
scheduler: StepLR
stage: edge_classifier
stage_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/pt>1GeV/400/gnn/
warmup: 5
weighting:
- conditions:
    y: false
  weight: 0.1
- conditions:
    y: true
  weight: 0.0
- conditions:
    nhits:
    - 3.0
    - .inf
    pt:
    - 1000.0
    - .inf
    y: true
  weight: 1.0
