accelerator: gpu
aggregation: sum
batchnorm: false
data_split:
- 50
- 50
- 50
devices: 4
dropout: 0.0
edge_cut: 0.5
edge_net_recurrent: true
factor: 0.9
hard_cuts:
  track_particle_pt:
  - 0.0
  - .inf
hidden: 128
hidden_activation: SiLU
hidden_dropout: 0.1
input_cut: 0.05
input_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/all_pt/50/filter/
input_dropout: 0.1
layernorm: true
lr: 0.001
max_epochs: 350
model: InteractionGNN
n_graph_iters: 8
nb_edge_layer: 2
nb_node_layer: 2
node_features:
- hit_r
- hit_phi
- hit_z
node_net_recurrent: true
node_scales:
- 1000
- 3.14
- 1000
nodes: 1
output_activation: Tanh
patience: 10
project: UQ_MCD_all_pt_gnn_50_HightPT_targets
ratio: 5
scheduler: StepLR
stage: edge_classifier
stage_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/all_pt/50/gnn/
track_running_stats: false
undirected: true
undirected_message_passing: true
warmup: 5
weighting:
- conditions:
    edge_y: false
  weight: 0.1
- conditions:
    edge_y: true
  weight: 0.0
- conditions:
    edge_y: true
    track_particle_nhits:
    - 3.0
    - .inf
    track_particle_pt:
    - 1000.0
    - .inf
  weight: 1.0
