MCDropout: true
accelerator: gpu
aggregation: sum
batchnorm: false
calibration: false
data_split:
- 50
- 50
- 50
devices: 1
dropout: 0.1
edge_cut: 0.5
factor: 0.9
hard_cuts:
  pt:
  - 0.0
  - .inf
hidden: 128
hidden_activation: SiLU
input_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/pt>1GeV/0/filter/
layernorm: true
lr: 0.001
max_epochs: 300
model: InteractionGNN
n_graph_iters: 8
n_train: 0
nb_MCD_passes: 100
nb_edge_layer: 2
nb_node_layer: 2
node_features:
- r
- phi
- z
node_scales:
- 1000
- 3.14
- 1000
nodes: 1
output_activation: Tanh
patience: 10
project: UQ_MCD_all_pt_gnn_50
ratio: 5
scheduler: StepLR
stage: edge_classifier
stage_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/pt>1GeV/0/gnn/
warmup: 5
weighting:
- conditions:
    nhits:
    - 3
    - .inf
    pt:
    - 0.0
    - .inf
    y: true
  weight: 1.0
