# CommonFramework configuration
stage: graph_construction
model: MetricLearning
input_dir: /pscratch/sd/l/lperon/ATLAS/data_dir/Example_3/feature_store/
stage_dir: /pscratch/sd/l/lperon/UQ_data/MCD/trackML/all_pt/50/metric_learning/
project: UQ_MCD_all_pt_metric_learning_50_HightPT_targets
accelerator: gpu
devices: 4 # Number of GPUs to use
nodes: 1

# Dataset parameters
data_split:
- 50   # training events
- 50   # validation events
- 50   # test events

# Truth and weighting parameters. The weight are use in the loss computation to account for edge contribution. The syntax is as follows:
# Single value: track[key] == value
# List of 2 floats: value1 <= track[key] <= value2
# List with a string as the first value: First value defines the boolean test, the second value is a list or value. Boolean tests are: (in, not_in, is, is_not, within, not_within)
# All other tracks follow the default: If a true edge, weight=0. If a fake edge, weight=1.

weighting:
- conditions: # Refered in the code as "fake edges"
    y: false
  weight: 1.0
- conditions: # Refered in the code as "true non target edges"
    y: true
  weight: 0.0
- conditions: # Refered in the code as "true target edges"
    nhits:
    - 3.0
    - .inf
    pt:
    - 1000.0
    - .inf
    y: true
  weight: 3.0

# A list of hard cut conditions. Any hits not passing these conditions will be removed from the training and validation dataset.
# By definition, noise will not pass any of these cuts, so any hard cuts will remove noise.
hard_cuts:
  pt:
  - 0.0
  - .inf

# Model parameters
undirected: true
node_features:
- r
- phi
- z
- cell_count
- cell_val
- leta
- lphi
- lx
- ly
- lz
- geta
- gphi
node_scales:
- 1000
- 3.14
- 1000
- 1
- 1
- 1
- 1
- 0.1
- 1
- 0.1
- 1
- 3.14
emb_hidden: 1024
nb_layer: 4
emb_dim: 12
activation: Tanh
input_dropout: 0      # see readme for details
hidden_dropout: 0   # see readme for details
randomisation: 1
points_per_batch: 100000
r_train: 0.1
knn: 100
knn_val: 1000

# Training parameters
factor: 0.7
lr: 0.01
margin: 0.1
max_epochs: 300
metric_mode: max
metric_to_monitor: f1
patience: 10
warmup: 5